#!/bin/sh

if test "$2" = ""; then
  echo USAGE:  topc-compare TOPC-1.tar.gz TOPC-2.tar.gz
  echo "        Finds essential differnces in two versions of TOP-C"
  exit 1
fi

DIR=/ccs/tmp/$USER

test -r $DIR || mkdir $DIR
rm -rf $DIR/topc-tmp
mkdir $DIR/topc-tmp

cp $1 $DIR/topc-tmp/topc-new.tar.gz
( cd $DIR/topc-tmp ; gzip -dc topc-new.tar.gz | tar xvf - ; \
  rm topc-new.tar.gz; mv topc-* tmp-new )

cp $2 $DIR/topc-tmp/topc-old.tar.gz
( cd $DIR/topc-tmp ; gzip -dc topc-old.tar.gz | tar xvf - ; \
  rm topc-old.tar.gz; mv topc-* tmp-old )

cd $DIR/topc-tmp
mv tmp-new topc-new
mv tmp-old topc-old

( cd topc-new; ./configure; make maintainer-clean )
( cd topc-old; ./configure; make maintainer-clean )
diff -r topc-new topc-old | tee topc-diff
echo ====================================================
grep -i only topc-diff
