#!/bin/sh

if test "$1" == ""; then
  echo "Usage:  ssh-killall PROCESS_NAME"
  echo "  PROCESS_NAME will be passed as arg to killall on each slave process"
  exit 1
fi

dir=/home/kason/school/4zp6/repo/GEANT4-GPU/topc-2.5.2/utils

if test ! -x $dir/ssh-procgroup; then
  echo "$dir:  gcc -o ssh-procgroup ssh-procgroup.c"
  ( cd $dir; gcc -o ssh-procgroup ssh-procgroup.c )
fi

$dir/ssh-procgroup killall -9 -v $1
